-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "movie" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_date" TIMESTAMPTZ(6) NOT NULL,
    "modified_date" TIMESTAMPTZ(6) NOT NULL,
    "available_globally" BOOL,
    "locale" STRING(10),
    "original_title" STRING(255),
    "release_date" DATE,
    "runtime" INT8,
    "title" STRING(255) NOT NULL,

    CONSTRAINT "movie_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "season" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_date" TIMESTAMPTZ(6) NOT NULL,
    "modified_date" TIMESTAMPTZ(6) NOT NULL,
    "original_title" STRING(255),
    "release_date" DATE,
    "runtime" INT8,
    "season_number" INT8,
    "title" STRING(255) NOT NULL,
    "tv_show_id" INT8,

    CONSTRAINT "season_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tv_show" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_date" TIMESTAMPTZ(6) NOT NULL,
    "modified_date" TIMESTAMPTZ(6) NOT NULL,
    "available_globally" BOOL,
    "locale" STRING(10),
    "original_title" STRING(255),
    "release_date" DATE,
    "title" STRING(255) NOT NULL,

    CONSTRAINT "tv_show_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "view_summary" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_date" TIMESTAMPTZ(6) NOT NULL,
    "modified_date" TIMESTAMPTZ(6) NOT NULL,
    "cumulative_weeks_in_top10" INT8,
    "duration" STRING(20) NOT NULL,
    "end_date" DATE NOT NULL,
    "hours_viewed" INT8 NOT NULL,
    "start_date" DATE NOT NULL,
    "view_rank" INT8,
    "views" INT8,
    "movie_id" INT8,
    "season_id" INT8,

    CONSTRAINT "view_summary_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "asset" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_date" TIMESTAMPTZ(6) NOT NULL,
    "modified_date" TIMESTAMPTZ(6) NOT NULL,
    "asset_type" STRING(50) NOT NULL,
    "url" STRING(255) NOT NULL,
    "movie_id" INT8,
    "tv_show_id" INT8,

    CONSTRAINT "asset_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "idx_movie_title_runtime" ON "movie"("title", "runtime");

-- CreateIndex
CREATE INDEX "idx_season_title_runtime" ON "season"("title", "runtime");

-- CreateIndex
CREATE INDEX "idx_season_tv_show_id" ON "season"("tv_show_id");

-- CreateIndex
CREATE UNIQUE INDEX "idx_tv_show_title" ON "tv_show"("title");

-- CreateIndex
CREATE INDEX "idx_asset_movie_id" ON "asset"("movie_id");

-- CreateIndex
CREATE INDEX "idx_asset_tv_show_id" ON "asset"("tv_show_id");

-- AddForeignKey
ALTER TABLE "season" ADD CONSTRAINT "fk_season_tv_show_id" FOREIGN KEY ("tv_show_id") REFERENCES "tv_show"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "view_summary" ADD CONSTRAINT "fk_view_summary_movie_id" FOREIGN KEY ("movie_id") REFERENCES "movie"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "view_summary" ADD CONSTRAINT "fk_view_summary_season_id" FOREIGN KEY ("season_id") REFERENCES "season"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "asset" ADD CONSTRAINT "fk_asset_movie_id" FOREIGN KEY ("movie_id") REFERENCES "movie"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "asset" ADD CONSTRAINT "fk_asset_tv_show_id" FOREIGN KEY ("tv_show_id") REFERENCES "tv_show"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

