/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Branding aliases
        brand: '#e50914',
        'brand-yellow': '#ffdb3c',
        'brand-dark': '#111317',
        'brand-text': '#e2e2e8',

        'surface-container-highest': '#333539',
        'on-secondary-container': '#725f00',
        'primary-fixed': '#ffdad5',
        'surface-variant': '#333539',
        'on-primary-container': '#fff7f6',
        'surface-container-lowest': '#0c0e12',
        'secondary-fixed-dim': '#e9c400',
        outline: '#af8782',
        primary: '#ffb4aa',
        'surface-container-high': '#282a2e',
        'on-surface': '#e2e2e8',
        'on-background': '#e2e2e8',
        'primary-container': '#e50914',
        'secondary-container': '#ffdb3c',
        'primary-fixed-dim': '#ffb4aa',
        'surface-dim': '#111317',
        'secondary-fixed': '#ffe16d',
        'surface-tint': '#ffb4aa',
        'on-primary': '#690003',
        'inverse-on-surface': '#2f3035',
        'error-container': '#93000a',
        'outline-variant': '#5e3f3b',
        'on-tertiary': '#00287d',
        'tertiary-fixed-dim': '#b5c4ff',
        'on-surface-variant': '#e9bcb6',
        background: '#111317',
        secondary: '#fff9ef',
        'on-secondary-fixed-variant': '#544600',
        'on-primary-fixed': '#410001',
        'on-tertiary-fixed-variant': '#153ea3',
        'tertiary-fixed': '#dce1ff',
        surface: '#111317',
        'tertiary-container': '#4c6cd2',
        'inverse-surface': '#e2e2e8',
        error: '#ffb4ab',
        'surface-bright': '#37393e',
        tertiary: '#b5c4ff',
        'on-error': '#690005',
        'surface-container': '#1e2024',
        'on-tertiary-container': '#faf8ff',
        'on-secondary-fixed': '#221b00',
        'surface-container-low': '#1a1c20',
        'on-tertiary-fixed': '#00164e',
        'inverse-primary': '#c0000c',
        'on-secondary': '#3a3000',
        'on-error-container': '#ffdad6',
        'on-primary-fixed-variant': '#930007',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Epilogue', 'sans-serif'],
        body: ['Work Sans', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
